### ISSUE TITLE
Investigate how to retrieve MongoDB metadata and information

### ISSUE THREAD

**Issue by cbiglioli** [ercole-io/ercole-agent#455]
Investigate how to retrieve MongoDB metadata and information.

You need to understand how to create fetchers for MongoDB.

**Comment by cbiglioli** [comment]
To run the tests, two environments were created, one with a single instance, the other a cluster.

**Comment by cbiglioli** [comment]
**Example output for a single instance**

`{
    "shardList": {
        "shards": null
    },
    "serverStatus": {
        "version": "6.0.1",
        "dbs": 2,
        "connections": {
            "current": 3,
            "available": 838857,
            "totalCreated": 3,
            "active": 2,
            "threaded": 3,
            "exhaustIsMaster": 0,
            "exhaustHello": 0,
            "awaitingTopologyChanges": 1,
            "loadBalanced": 0
        }
    },
    "dbStats": [
        {
            "dbName": "ercole",
            "collections": 20,
            "views": 1,
            "objects": 727,
            "indexes": 29,
            "dataSize": 1358956,
            "indexSize": 876544,
            "storageSize": 995328,
            "totalSize": 1871872,
            "fsUsedSize": 28157669376,
            "fsTotalSize": 269490393088,
            "freeStorageSize": 344064,
            "indexFreeStorageSize": 315392,
            "totalFreeStorageSize": 659456,
            "users": 2
        },
        {
            "dbName": "test",
            "collections": 1,
            "views": 0,
            "objects": 0,
            "indexes": 1,
            "dataSize": 0,
            "indexSize": 4096,
            "storageSize": 4096,
            "totalSize": 8192,
            "fsUsedSize": 28157669376,
            "fsTotalSize": 269490393088,
            "freeStorageSize": 0,
            "indexFreeStorageSize": 0,
            "totalFreeStorageSize": 0,
            "users": 0
        }
    ]
}
`

**Comment by cbiglioli** [comment]
### Other info

**Comment by cbiglioli** [comment]
### Analysis

It can be used commands directly on MongoDB server by using the **RunCommand()** method to retrieve server information:
https://www.mongodb.com/docs/drivers/go/current/usage-examples/command/
This way you can use the agent code written in Go and is valid for both Linux and Windows installations.

To retrieve the installed MongoDB version and server connection information, run the following command: **serverStatus**:
https://www.mongodb.com/docs/manual/reference/method/db.serverStatus/
The following information are retrieved through the serverStatus command:

- **version**: version of MongoDB.
- **connections.current**: the number of incoming connections from clients to the database server.
- **connections.active**: the number of active client connections to the server.
- **connections.available**: the number of unused incoming connections available.
- **connections.totalCreated**: count of all incoming connections created to the server.
- **connections.threaded**: the number of incoming connections from clients that are assigned to threads that service client requests.
- **connections.exhaustIsMaster**: the number of connections whose last request was an isMaster request with exhaustAllowed.
- **connections.exhaustHello**: the number of connections whose last request was a hello request with exhaustAllowed.
- **connections.awaitingTopologyChanges**: the number of clients currently waiting in a hello or isMaster request for a topology change.
- **connections.loadBalanced**: the current number of incoming connections received through the load balancer.

For more information about connections: 
https://www.mongodb.com/docs/manual/reference/command/serverStatus/#connections

To retrieve the list of databases, execute **ListDatabaseNames** (Go): ListDatabaseNames executes a listDatabases command and returns a slice containing the names of all of the databases on the server.
The following system databases should be excluded from the database list: 

- **admin**
- **config**
- **local**

The number of databases is calculated each time a database is analyzed.

For each database, the following information was collected using the **stats** command:

- **collections**: number of collections in the database.
- **views**: number of views in the database.
- **fsUsedSize** _(bytes)_: total size of all disk space in use on the filesystem where MongoDB stores data.
- **fsTotalSize** _(bytes)_: total size of all disk capacity on the filesystem where MongoDB stores data.
- **freeStorageSize** _(bytes)_: sum of the free space allocated to all collections in the database for document storage. Free database storage space is allocated to the collection but does not contain data.
- **indexFreeStorageSize** _(bytes)_: sum of the free space allocated to all indexes in the database. Free database storage space is allocated to the index but does not contain data.
- **totalFreeStorageSize** _(bytes)_: sum of the free storage space allocated for both documents and indexes in all collections in the database. This is the sum of 
freeStorageSize and indexFreeStorageSize.
- **dataSize** _(bytes)_: total size of the uncompressed data held in the database.
- **indexSize** _(bytes)_: sum of the space allocated to all indexes in the database, including free index space.
- **storageSize** _(bytes)_: sum of the space allocated to all collections in the database for document storage, including free space.
- **totalSize** _(bytes)_: sum of the space allocated for both documents and indexes in all collections in the database. Includes used and free storage space. This is the sum of storageSize and indexSize.
- **objects**: number of objects (specifically, documents) in the database across all collections.
- **indexes**: total number of indexes across all collections in the database.

To include freeStorageSize, indexFreeStorageSize and totalFreeStorageSize in the output, you need to add **freeStorage = 1** to the stats command.

For more information about the stats command:
https://www.mongodb.com/docs/manual/reference/method/db.stats/
https://www.mongodb.com/docs/manual/reference/command/dbStats/#std-label-dbstats-output

To retrieve the number of users in each database, use the **usersInfo** command:
https://www.mongodb.com/docs/manual/reference/command/usersInfo/
Once the information is retrieved, the length of the returned array is calculated.

Regarding the **charset**, no data is retrieved because MongoDB stores all documents using the BSON format and BSON spec referes to a UTF-8 string encoding: 
https://bsonspec.org/spec.html
https://www.mongodb.com/docs/manual/reference/bson-types/

**Comment by cbiglioli** [comment]
### Testing environment

_To run the tests, two environments were created, one with a single instance, the other a cluster._

**Single instance**

For example, to create the test environment in Docker for the single instance, run:

`docker create --name test-db -p 27017:27017 mongo:6.0`

**Cluster**

For example, to create the test environment in Docker for cluster, run:

`docker compose up`

in the same folder where the yml file is present.

File yml:

```
version: '2'

services:
  mongodb-sharded:
    image: docker.io/bitnami/mongodb-sharded:6.0
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-sharded
      - MONGODB_SHARDING_MODE=mongos
      - MONGODB_CFG_PRIMARY_HOST=mongodb-cfg
      - MONGODB_CFG_REPLICA_SET_NAME=cfgreplicaset
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
      - MONGODB_ROOT_PASSWORD=password123
    ports:
      - "27017:27017"

  mongodb-shard0:
    image: docker.io/bitnami/mongodb-sharded:6.0
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-shard0
      - MONGODB_SHARDING_MODE=shardsvr
      - MONGODB_MONGOS_HOST=mongodb-sharded
      - MONGODB_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
      - MONGODB_REPLICA_SET_NAME=shard0
    volumes:
      - 'shard0_data:/bitnami'

  mongodb-cfg:
    image: docker.io/bitnami/mongodb-sharded:6.0
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-cfg
      - MONGODB_SHARDING_MODE=configsvr
      - MONGODB_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
      - MONGODB_REPLICA_SET_NAME=cfgreplicaset
    volumes:
      - 'cfg_data:/bitnami'

volumes:
  shard0_data:
    driver: local
  cfg_data:
    driver: local

```

For more information about the cluster and yml files: https://hub.docker.com/r/bitnami/mongodb-sharded/

**Comment by cbiglioli** [comment]
### Output examples

_Here are two useful examples, one for a single instance, the other for the cluster, of fetcher output._

**Example output for a single instance**


```
{
    "shardList": {
        "shards": null
    },
    "serverStatus": {
        "version": "6.0.1",
        "dbs": 2,
        "connections": {
            "current": 3,
            "available": 838857,
            "totalCreated": 3,
            "active": 2,
            "threaded": 3,
            "exhaustIsMaster": 0,
            "exhaustHello": 0,
            "awaitingTopologyChanges": 1,
            "loadBalanced": 0
        }
    },
    "dbStats": [
        {
            "dbName": "ercole",
            "collections": 20,
            "views": 1,
            "objects": 727,
            "indexes": 29,
            "dataSize": 1358956,
            "indexSize": 876544,
            "storageSize": 995328,
            "totalSize": 1871872,
            "fsUsedSize": 28157669376,
            "fsTotalSize": 269490393088,
            "freeStorageSize": 344064,
            "indexFreeStorageSize": 315392,
            "totalFreeStorageSize": 659456,
            "users": 2
        },
        {
            "dbName": "test",
            "collections": 1,
            "views": 0,
            "objects": 0,
            "indexes": 1,
            "dataSize": 0,
            "indexSize": 4096,
            "storageSize": 4096,
            "totalSize": 8192,
            "fsUsedSize": 28157669376,
            "fsTotalSize": 269490393088,
            "freeStorageSize": 0,
            "indexFreeStorageSize": 0,
            "totalFreeStorageSize": 0,
            "users": 0
        }
    ]
}
```

**Example output for cluster**

```
{
    "shardList": {
        "shards": [
            {
                "_id": "shard0",
                "host": "shard0/mongodb-shard0:27017",
                "state": 1
            }
        ]
    },
    "serverStatus": {
        "version": "6.0.4",
        "dbs": 2,
        "connections": {
            "current": 15,
            "available": 838845,
            "totalCreated": 27,
            "active": 4,
            "threaded": 15,
            "exhaustIsMaster": 0,
            "exhaustHello": 2,
            "awaitingTopologyChanges": 3,
            "loadBalanced": 0
        }
    },
    "dbStats": [
        {
            "dbName": "test",
            "collections": 3,
            "views": 1,
            "objects": 1,
            "indexes": 3,
            "dataSize": 90,
            "indexSize": 28672,
            "storageSize": 28672,
            "totalSize": 57344,
            "fsUsedSize": 28160212992,
            "fsTotalSize": 269490393088,
            "freeStorageSize": 0,
            "indexFreeStorageSize": 0,
            "totalFreeStorageSize": 0,
            "users": 1
        },
        {
            "dbName": "test2",
            "collections": 2,
            "views": 0,
            "objects": 0,
            "indexes": 2,
            "dataSize": 0,
            "indexSize": 8192,
            "storageSize": 8192,
            "totalSize": 16384,
            "fsUsedSize": 28160212992,
            "fsTotalSize": 269490393088,
            "freeStorageSize": 0,
            "indexFreeStorageSize": 0,
            "totalFreeStorageSize": 0,
            "users": 0
        }
    ]
}
```

**Comment by cbiglioli** [comment]
### Other info

Below is the link to download MongoDB with all its supported operating systems:

https://www.mongodb.com/download-center/community/releases

**Comment by cbiglioli** [comment]
### Testing environment

_To run the tests, two environments were created, one with a single instance, the other a cluster._

**Single instance**

For example, to create the test environment in Docker for the single instance, run:

`docker create --name test-db -p 27017:27017 mongo:6.0`

**Cluster**

For example, to create the test environment in Docker for cluster, run:

`docker compose up`

in the same folder where the yml file is present.

File yml:

```
version: '2'

services:
  mongodb-sharded:
    image: docker.io/bitnami/mongodb-sharded:6.0
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-sharded
      - MONGODB_SHARDING_MODE=mongos
      - MONGODB_CFG_PRIMARY_HOST=mongodb-cfg
      - MONGODB_CFG_REPLICA_SET_NAME=cfgreplicaset
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
      - MONGODB_ROOT_PASSWORD=password123
    ports:
      - "27017:27017"

  mongodb-shard0:
    image: docker.io/bitnami/mongodb-sharded:6.0
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-shard0
      - MONGODB_SHARDING_MODE=shardsvr
      - MONGODB_MONGOS_HOST=mongodb-sharded
      - MONGODB_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
      - MONGODB_REPLICA_SET_NAME=shard0
    volumes:
      - 'shard0_data:/bitnami'

  mongodb-cfg:
    image: docker.io/bitnami/mongodb-sharded:6.0
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-cfg
      - MONGODB_SHARDING_MODE=configsvr
      - MONGODB_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
      - MONGODB_REPLICA_SET_NAME=cfgreplicaset
    volumes:
      - 'cfg_data:/bitnami'

volumes:
  shard0_data:
    driver: local
  cfg_data:
    driver: local

```

For more information about the cluster and yml files: https://hub.docker.com/r/bitnami/mongodb-sharded/
